 上位机和下位机[platformio]
src_dir = main
include_dir = main/include

[env:esp32-c3-mini-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
upload_speed = 460800
build_type = debug